In [826]:
import pandas as pd
import numpy as np
import sklearn as sk
import matplotlib.pyplot as plt
from sklearn import linear_model
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, OrdinalEncoder, MinMaxScaler, PolynomialFeatures
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score
oe = OrdinalEncoder()
le = LabelEncoder()
ohe = OneHotEncoder()
import seaborn as sns

In [827]:
df_main = pd.read_csv('/Users/apple/Desktop/Projects/Review Data Science/Messy_Employment_India_Dataset.csv')
df_main.head()

,Status,Age Group,Education,Industry,Location,AI Risk,Years of Experience,Monthly Salary (INR),Date Recorded
0,EMPLOYED,25_34,high school,Technology,Urban,NaN,NaN,40700.0,1/1/2023
1,EMPLOYED,18-24,Diploma,Fintech,rural,moderate,NaN,17500.0,1/2/2023
2,EMPLOYED,25_34,High School,Retail,Delhi,Low,16.0,77600.0,1/3/2023
3,UNEMPLOYED,18-24,Masters,Retail,Urban,Low,30.0,100200.0,1/4/2023
4,NaN,45-54,Diploma,Fintech,Hyderabad,low,9.0,19500.0,1/5/2023

In [828]:
df_main.index

RangeIndex(start=0, stop=2000, step=1)

In [829]:
df_main.columns

Index(['Status', 'Age Group', 'Education', 'Industry', 'Location', 'AI Risk',
       'Years of Experience', 'Monthly Salary (INR)', 'Date Recorded'],
      dtype='object')

In [830]:
'Age Group' in df_main

True

In [831]:
df_main.index.is_monotonic_increasing
df_main.index.is_unique

True

In [832]:
df_main.loc[[10,100,1000,1053],['Status','Education','AI Risk','Years of Experience']]

          Status Education AI Risk  Years of Experience
10    Unemployed    Master    High                  NaN
100     employed       PhD     NaN                  NaN
1000  unemployed   Diploma    High                  NaN
1053    employed       PhD    HIGH                  NaN

In [833]:
df_main.columns
df_main.tail()

,Status,Age Group,Education,Industry,Location,AI Risk,Years of Experience,Monthly Salary (INR),Date Recorded
1995,employed,25-34,Ph.D,Finance,Hyderabad,Low,NaN,113000.0,6/18/2028
1996,EMPLOYED,25-34,PhD,Tech,NaN,NaN,22.0,102200.0,6/19/2028
1997,NaN,35 - 44,Masters,Education,NaN,low,NaN,31600.0,6/20/2028
1998,EMPLOYED,25_34,high school,Retail,Mumbai,HIGH,22.0,92500.0,6/21/2028
1999,UNEMPLOYED,25_34,High School,NaN,NaN,moderate,NaN,43300.0,6/22/2028

In [834]:
df_main.Status.value_counts()

Status
Employed      302
employed      297
UNEMPLOYED    289
EMPLOYED      286
unemployed    283
Unemployed    275
Name: count, dtype: int64

In [835]:
df_main['Age Group'].value_counts()

Age Group
18 to 24    262
45-54       261
18-24       256
25_34       254
35 - 44     247
55+         244
25-34       244
Name: count, dtype: int64

In [836]:
df_main['AI Risk'].value_counts()

AI Risk
HIGH        308
Low         293
High        288
moderate    285
Medium      279
low         263
Name: count, dtype: int64

In [837]:
df_main['Date Recorded'].value_counts()

Date Recorded
1/1/2023      1
8/22/2026     1
9/4/2026      1
9/3/2026      1
9/2/2026      1
             ..
10/23/2024    1
10/22/2024    1
10/21/2024    1
10/20/2024    1
6/22/2028     1
Name: count, Length: 2000, dtype: int64

In [838]:
df_main.drop(columns = 'Date Recorded', inplace=True)

In [839]:
df_main.columns

Index(['Status', 'Age Group', 'Education', 'Industry', 'Location', 'AI Risk',
       'Years of Experience', 'Monthly Salary (INR)'],
      dtype='object')

In [840]:
df_main[['Location']].value_counts()

Location
Bangalore    233
Delhi        233
suburban     231
urban        227
Mumbai       226
Hyderabad    215
Urban        211
rural        211
Name: count, dtype: int64

In [841]:
df_main[['Age Group']].value_counts()

Age Group
18 to 24     262
45-54        261
18-24        256
25_34        254
35 - 44      247
25-34        244
55+          244
Name: count, dtype: int64

In [842]:
df_main[['Years of Experience']].value_counts()

Years of Experience
26.0                   42
20.0                   42
16.0                   41
5.0                    40
7.0                    40
22.0                   39
29.0                   36
28.0                   36
18.0                   36
0.0                    35
10.0                   34
1.0                    34
2.0                    33
25.0                   32
3.0                    31
24.0                   31
21.0                   30
27.0                   29
30.0                   29
13.0                   29
11.0                   29
6.0                    29
19.0                   28
14.0                   28
23.0                   28
9.0                    27
17.0                   26
8.0                    24
4.0                    21
15.0                   21
12.0                   20
Name: count, dtype: int64

In [843]:
df_main['AI Risk'] = df_main['AI Risk'].replace(['HIGH','High'], 'H')
df_main['AI Risk']

0            NaN
1       moderate
2            Low
3            Low
4            low
          ...
1995         Low
1996         NaN
1997         low
1998           H
1999    moderate
Name: AI Risk, Length: 2000, dtype: object

In [844]:
df_main['AI Risk'].value_counts()

AI Risk
H           596
Low         293
moderate    285
Medium      279
low         263
Name: count, dtype: int64

In [845]:
df_main['AI Risk'] = df_main['AI Risk'].replace(['Low','low'], 'L')
df_main['AI Risk'] = df_main['AI Risk'].replace(['moderate','Medium'], 'M')
df_main['AI Risk'].value_counts()

AI Risk
H    596
M    564
L    556
Name: count, dtype: int64

In [846]:
df_main.Education.value_counts()
df_main.Education = df_main.Education.replace(['Bachelors',"Bachelor's"], 'Undergraduate')
df_main.Education = df_main.Education.replace(['Masters','Master'], 'Graduate')
df_main.Education = df_main.Education.replace(['PhD','Ph.D'], 'Postgraduate')
df_main.Education = df_main.Education.replace(['High School','high school'], 'High school')
df_main.Education.value_counts()

Education
Undergraduate    425
Postgraduate     400
Graduate         398
High school      377
Diploma          204
Name: count, dtype: int64

In [847]:
df_ready = df_main[['Education', 'AI Risk']]
df_ready.head()

     Education AI Risk
0  High school     NaN
1      Diploma       M
2  High school       L
3     Graduate       L
4      Diploma       L

In [848]:
df_main.Location = df_main.Location.replace(['Urban','urban'], 'Urban')
df_main.Location = df_main.Location.replace(['suburban'], 'Suburban')
df_main.Location = df_main.Location.replace(['rural'], 'Rural')
df_main.Location.value_counts()

Location
Urban        438
Delhi        233
Bangalore    233
Suburban     231
Mumbai       226
Hyderabad    215
Rural        211
Name: count, dtype: int64

In [849]:
df_ready['Location'] = df_main.Location
df_ready.head()

/var/folders/5m/_3qkn6w92px2cw4htvc6m0j80000gn/T/ipykernel_97103/3107735868.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_ready['Location'] = df_main.Location

     Education AI Risk   Location
0  High school     NaN      Urban
1      Diploma       M      Rural
2  High school       L      Delhi
3     Graduate       L      Urban
4      Diploma       L  Hyderabad

In [850]:
df_main.Status = df_main.Status.replace(['Employed','employed','EMPLOYED'], 'Employed')
df_main.Status = df_main.Status.replace(['UNEMPLOYED','unemployed','Unemployed'], 'Unemployed')
df_main.Status.value_counts()

Status
Employed      885
Unemployed    847
Name: count, dtype: int64

In [851]:
df_ready['Status'] =  df_main[['Status']]
df_ready.head()

/var/folders/5m/_3qkn6w92px2cw4htvc6m0j80000gn/T/ipykernel_97103/4026965441.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_ready['Status'] =  df_main[['Status']]

     Education AI Risk   Location      Status
0  High school     NaN      Urban    Employed
1      Diploma       M      Rural    Employed
2  High school       L      Delhi    Employed
3     Graduate       L      Urban  Unemployed
4      Diploma       L  Hyderabad         NaN

In [852]:
df_main.head()
df_main.Industry.value_counts()

Industry
Retail        429
Health        211
Healthcare    207
 Fintech      194
Finance       194
Education     193
Technology    186
Tech          185
Name: count, dtype: int64

In [853]:
df_main.Industry = df_main.Industry.replace(['Healthcare','Health'], 'Healthcare')
df_main.Industry = df_main.Industry.replace([' Fintech'], 'Fintech')
df_main.Industry = df_main.Industry.replace(['Technology','Tech '], 'Technology')
df_ready['Industry'] =  df_main[['Industry']]
df_ready.Industry.value_counts()
df_ready.head()
df_main.head()

/var/folders/5m/_3qkn6w92px2cw4htvc6m0j80000gn/T/ipykernel_97103/4291336033.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_ready['Industry'] =  df_main[['Industry']]

,Status,Age Group,Education,Industry,Location,AI Risk,Years of Experience,Monthly Salary (INR)
0,Employed,25_34,High school,Technology,Urban,NaN,NaN,40700.0
1,Employed,18-24,Diploma,Fintech,Rural,M,NaN,17500.0
2,Employed,25_34,High school,Retail,Delhi,L,16.0,77600.0
3,Unemployed,18-24,Graduate,Retail,Urban,L,30.0,100200.0
4,NaN,45-54,Diploma,Fintech,Hyderabad,L,9.0,19500.0

In [854]:
df_main['Age Group'].value_counts()
df_main['Age Group'] =  df_main['Age Group'].replace(['18 to 24','18-24'],'18-24')
df_main['Age Group'] =  df_main['Age Group'].replace(['25_34','25-34'],'25-34')
df_main['Age Group'] =  df_main['Age Group'].replace(['35 - 44'],'35-44')
df_main['Age Group'].value_counts()

Age Group
18-24    518
25-34    498
45-54    261
35-44    247
55+      244
Name: count, dtype: int64

In [855]:
df_ready['Ages'] = df_main['Age Group']
df_ready.head()

/var/folders/5m/_3qkn6w92px2cw4htvc6m0j80000gn/T/ipykernel_97103/276136891.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_ready['Ages'] = df_main['Age Group']

     Education AI Risk   Location      Status    Industry   Ages
0  High school     NaN      Urban    Employed  Technology  25-34
1      Diploma       M      Rural    Employed     Fintech  18-24
2  High school       L      Delhi    Employed      Retail  25-34
3     Graduate       L      Urban  Unemployed      Retail  18-24
4      Diploma       L  Hyderabad         NaN     Fintech  45-54

In [856]:
df_ready['Experience'] = df_main['Years of Experience']
df_ready['Salary'] = df_main['Monthly Salary (INR)']
df_ready.Experience
df_ready.head()

/var/folders/5m/_3qkn6w92px2cw4htvc6m0j80000gn/T/ipykernel_97103/1094454330.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_ready['Experience'] = df_main['Years of Experience']

,Education,AI Risk,Location,Status,Industry,Ages,Experience,Salary
0,High school,NaN,Urban,Employed,Technology,25-34,NaN,40700.0
1,Diploma,M,Rural,Employed,Fintech,18-24,NaN,17500.0
2,High school,L,Delhi,Employed,Retail,25-34,16.0,77600.0
3,Graduate,L,Urban,Unemployed,Retail,18-24,30.0,100200.0
4,Diploma,L,Hyderabad,NaN,Fintech,45-54,9.0,19500.0

In [857]:
print(df_main.columns, df_ready.columns)

Index(['Status', 'Age Group', 'Education', 'Industry', 'Location', 'AI Risk',
       'Years of Experience', 'Monthly Salary (INR)'],
      dtype='object') Index(['Education', 'AI Risk', 'Location', 'Status', 'Industry', 'Ages',
       'Experience', 'Salary'],
      dtype='object')

It is getting to complicated with tons of new lines, I have to learn how to simplify these lines! I cleaned changed values to readable, and usable data

In [858]:
df_ready.isnull().sum()

Education      196
AI Risk        284
Location       213
Status         268
Industry       201
Ages           232
Experience    1020
Salary         387
dtype: int64

Here we can see that NaN values in Experience column are lot, we have 2 options: dropping the column or by analyzing we can decide to change Nan values into 0, coz NaN might also mean no experience, we have to analyze it!

In [859]:
df_ready.head(100)

,Education,AI Risk,Location,Status,Industry,Ages,Experience,Salary
0,High school,NaN,Urban,Employed,Technology,25-34,NaN,40700.0
1,Diploma,M,Rural,Employed,Fintech,18-24,NaN,17500.0
2,High school,L,Delhi,Employed,Retail,25-34,16.0,77600.0
3,Graduate,L,Urban,Unemployed,Retail,18-24,30.0,100200.0
4,Diploma,L,Hyderabad,NaN,Fintech,45-54,9.0,19500.0
...,...,...,...,...,...,...,...,...
95,Postgraduate,L,Hyderabad,Unemployed,Fintech,25-34,26.0,NaN
96,Diploma,M,Hyderabad,Employed,Healthcare,25-34,NaN,NaN
97,Postgraduate,H,Urban,Employed,NaN,25-34,2.0,8900.0
98,Diploma,H,Hyderabad,Unemployed,Retail,25-34,NaN,124300.0
99,Postgraduate,L,NaN,Employed,Healthcare,45-54,12.0,141400.0

In [860]:
df_ready.value_counts()

Education      AI Risk  Location   Status      Industry    Ages   Experience  Salary
Diploma        H        Bangalore  Employed    Finance     25-34  21.0        39700.0     1
Postgraduate   L        Rural      Unemployed  Healthcare  35-44  5.0         43100.0     1
                        Urban      Unemployed  Retail      18-24  17.0        71300.0     1
                                               Healthcare  25-34  10.0        90800.0     1
                                               Fintech     18-24  10.0        7200.0      1
                                                                                         ..
Graduate       M        Urban      Unemployed  Retail      25-34  24.0        64900.0     1
                                               Healthcare  18-24  11.0        52900.0     1
                                   Employed    Education   25-34  28.0        137400.0    1
                        Suburban   Unemployed  Technology  55+    18.0        127100.0    1
Undergraduate  M        Urban      Unemployed  Education   35-44  20.0        78600.0     1
Name: count, Length: 383, dtype: int64

In [861]:
df_ready['Experience'].fillna(df_ready.Experience.mean(), inplace=True)
df_ready.dropna(inplace=True)
df_ready.head()

/var/folders/5m/_3qkn6w92px2cw4htvc6m0j80000gn/T/ipykernel_97103/783185146.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_ready['Experience'].fillna(df_ready.Experience.mean(), inplace=True)

,Education,AI Risk,Location,Status,Industry,Ages,Experience,Salary
1,Diploma,M,Rural,Employed,Fintech,18-24,15.244898,17500.0
2,High school,L,Delhi,Employed,Retail,25-34,16.000000,77600.0
3,Graduate,L,Urban,Unemployed,Retail,18-24,30.000000,100200.0
5,Postgraduate,H,Bangalore,Unemployed,Technology,25-34,15.244898,54500.0
11,High school,H,Delhi,Unemployed,Technology,45-54,15.244898,27000.0

In [862]:
df_ready.value_counts()
#df_ready.Education.value_counts()

Education      AI Risk  Location   Status      Industry    Ages   Experience  Salary
Diploma        H        Bangalore  Employed    Finance     25-34  21.000000   39700.0     1
Postgraduate   L        Suburban   Employed    Retail      25-34  15.244898   118800.0    1
                        Rural      Employed    Technology  18-24  15.244898   121700.0    1
                                   Unemployed  Healthcare  18-24  24.000000   122900.0    1
                                                           25-34  20.000000   118600.0    1
                                                                                         ..
High school    H        Bangalore  Employed    Fintech     25-34  15.244898   94100.0     1
                                   Unemployed  Education   25-34  21.000000   144100.0    1
                                               Finance     25-34  15.244898   118100.0    1
                                               Fintech     18-24  15.244898   123100.0    1
Undergraduate  M        Urban      Unemployed  Technology  35-44  15.244898   13300.0     1
Name: count, Length: 759, dtype: int64

In [863]:
edu_order = [['High school', 'Diploma', 'Undergraduate', 'Graduate','Postgraduate']]
edu_ordinal_encoder = OrdinalEncoder(categories=edu_order)
df_ready['Education_Encoded']= edu_ordinal_encoder.fit_transform(df_ready[['Education']])

ai_risk_order = [['L','M','H']]
risk_ordinal_encoder = OrdinalEncoder(categories=ai_risk_order)
df_ready['AI_risk_Encoded']= risk_ordinal_encoder.fit_transform(df_ready[['AI Risk']])

status_order = [['Unemployed','Employed']]
status_ordinal_encoder = OrdinalEncoder(categories=status_order)
df_ready['Status_Encoded']= status_ordinal_encoder.fit_transform(df_ready[['Status']])

df_ready.head(10)

,Education,AI Risk,Location,Status,Industry,Ages,Experience,Salary,Education_Encoded,AI_risk_Encoded,Status_Encoded
1,Diploma,M,Rural,Employed,Fintech,18-24,15.244898,17500.0,1.0,1.0,1.0
2,High school,L,Delhi,Employed,Retail,25-34,16.000000,77600.0,0.0,0.0,1.0
3,Graduate,L,Urban,Unemployed,Retail,18-24,30.000000,100200.0,3.0,0.0,0.0
5,Postgraduate,H,Bangalore,Unemployed,Technology,25-34,15.244898,54500.0,4.0,2.0,0.0
11,High school,H,Delhi,Unemployed,Technology,45-54,15.244898,27000.0,0.0,2.0,0.0
13,Postgraduate,L,Rural,Employed,Technology,18-24,15.244898,121700.0,4.0,0.0,1.0
15,Undergraduate,M,Bangalore,Unemployed,Healthcare,18-24,18.000000,28700.0,2.0,1.0,0.0
16,High school,L,Urban,Employed,Retail,25-34,15.244898,109300.0,0.0,0.0,1.0
24,Postgraduate,M,Hyderabad,Unemployed,Technology,25-34,24.000000,107700.0,4.0,1.0,0.0
29,Graduate,L,Urban,Employed,Healthcare,18-24,15.000000,13300.0,3.0,0.0,1.0

In [864]:
ohe = OneHotEncoder(drop='first', sparse_output=False)
columns_to_encode = ['Location','Industry','Ages']
encoded_array = ohe.fit_transform(df_ready[columns_to_encode])
new_column_names = ohe.get_feature_names_out(columns_to_encode)
encoded_df = pd.DataFrame(encoded_array, columns=new_column_names, index=df_ready.index)
df_ready = pd.concat([df_ready, encoded_df], axis=1)
df_ready.drop(columns=columns_to_encode, inplace=True)
df_ready.head()
df_ready.shape

(759, 23)

In [865]:
df_ready.drop(columns=['Education','AI Risk','Status'], inplace=True)
df_ready.head()

,Experience,Salary,Education_Encoded,AI_risk_Encoded,Status_Encoded,Location_Delhi,Location_Hyderabad,Location_Mumbai,Location_Rural,Location_Suburban,Location_Urban,Industry_Finance,Industry_Fintech,Industry_Healthcare,Industry_Retail,Industry_Technology,Ages_25-34,Ages_35-44,Ages_45-54,Ages_55+
1,15.244898,17500.0,1.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,16.000000,77600.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0
3,30.000000,100200.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
5,15.244898,54500.0,4.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
11,15.244898,27000.0,0.0,2.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0

# Normalizing dataset

In [866]:
min_max = MinMaxScaler(feature_range=(0,1))
columns_to_normalize = ['Experience','Salary']

df_ready[columns_to_normalize] = min_max.fit_transform(df_ready[columns_to_normalize])
df_ready.head(10)

,Experience,Salary,Education_Encoded,AI_risk_Encoded,Status_Encoded,Location_Delhi,Location_Hyderabad,Location_Mumbai,Location_Rural,Location_Suburban,Location_Urban,Industry_Finance,Industry_Fintech,Industry_Healthcare,Industry_Retail,Industry_Technology,Ages_25-34,Ages_35-44,Ages_45-54,Ages_55+
1,0.508163,0.085635,1.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.533333,0.500691,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0
3,1.000000,0.656768,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
5,0.508163,0.341160,4.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
11,0.508163,0.151243,0.0,2.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
13,0.508163,0.805249,4.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
15,0.600000,0.162983,2.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
16,0.508163,0.719613,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0
24,0.800000,0.708564,4.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
29,0.500000,0.056630,3.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0

# Modelling, and predicting salaries

In [867]:
lr = linear_model.LinearRegression()
logistic_reg = linear_model.LogisticRegression()

In [868]:
X = df_ready[['Experience', 'Education_Encoded', 'AI_risk_Encoded',
       'Status_Encoded', 'Location_Delhi', 'Location_Hyderabad',
       'Location_Mumbai', 'Location_Rural', 'Location_Suburban',
       'Location_Urban', 'Industry_Finance', 'Industry_Fintech',
       'Industry_Healthcare', 'Industry_Retail', 'Industry_Technology',
       'Ages_25-34', 'Ages_35-44', 'Ages_45-54', 'Ages_55+']] # Features
y = df_ready['Salary']                 # Target variable

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [869]:
linear_model = lr.fit(X_train,y_train)

y_pred = linear_model.predict(X_test)

mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)

# 3. Calculate R-squared
r2 = r2_score(y_test, y_pred)

print(f"Mean Squared Error (MSE): {mse:.2f}")
print(f"Root Mean Squared Error (RMSE): {rmse:.2f}")
print(f"R-squared (R2) Score: {r2:.4f}")

Mean Squared Error (MSE): 0.08
Root Mean Squared Error (RMSE): 0.29
R-squared (R2) Score: 0.0143

In [871]:
salary_scaler = MinMaxScaler() 

salary_scaler.fit(df_ready[['Salary']])

real_y_test = salary_scaler.inverse_transform(np.array(y_test).reshape(-1, 1))
real_y_pred = salary_scaler.inverse_transform(np.array(y_pred).reshape(-1, 1))


# ---------------------------------------------------------
# STEP 3: Create a clean DataFrame to see the actual differences!
# ---------------------------------------------------------
# .flatten() converts the 2D array back into a flat list for the table
results_df = pd.DataFrame({
    'Actual Salary ($)': real_y_test.flatten(),
    'Predicted Salary ($)': real_y_pred.flatten()
})

# Calculate the real-world dollar error for every single guess!
results_df['Difference ($)'] = results_df['Predicted Salary ($)'] - results_df['Actual Salary ($)']

# Round the numbers so they look like real money
results_df = results_df.round(2)

print("--- REAL WORLD DOLLAR DIFFERENCES ---")
print(results_df.head(10))

--- REAL WORLD DOLLAR DIFFERENCES ---
   Actual Salary ($)  Predicted Salary ($)  Difference ($)
0               0.82                  0.49           -0.33
1               0.50                  0.50           -0.01
2               0.52                  0.49           -0.03
3               0.66                  0.46           -0.20
4               0.20                  0.50            0.30
5               0.56                  0.45           -0.11
6               0.30                  0.45            0.15
7               0.69                  0.42           -0.28
8               0.23                  0.53            0.30
9               0.03                  0.46            0.43